"""Fix user and restourant relation

Revision ID: 4c25cb2ca8a5
Revises: 82163bef116c
Create Date: 2024-06-19 20:36:50.237777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c25cb2ca8a5'
down_revision: Union[str, None] = '82163bef116c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'restaurant', 'user', ['user_id'], ['user_id'])
    op.drop_column('restaurant', 'alamat')
    op.drop_column('restaurant', 'nomor_telepon')
    op.drop_column('restaurant', 'nama_restoran')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('nama_restoran', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('restaurant', sa.Column('nomor_telepon', mysql.VARCHAR(length=15), nullable=False))
    op.add_column('restaurant', sa.Column('alamat', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    # ### end Alembic commands ###
