"""Add role column to user table

Revision ID: 82163bef116c
Revises: 
Create Date: 2024-06-19 19:37:54.318648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82163bef116c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.alter_column('menu', 'harga',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.alter_column('menu', 'harga',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.create_table('order',
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('items', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('total_harga', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], name='order_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='order_ibfk_1'),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
